/**
 * Gate L3: snapshots. For every snippet, `pattern.sortHapsByPart().queryArc(0, cycles)`
 * formatted with `hap.show(true)` (exactly like Strudel's own snapshot tests), plus the cps,
 * must equal the committed golden file `__snapshots__/<id>.snap` (one file per variant or
 * lesson). A missing snapshot fails unless `--update` is given; `--update` rewrites files and
 * deletes stale ones. Review the git diff of __snapshots__/ after updating.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { ValidContent } from '../content/model.js';
import type { Snippet } from '../content/snippets.js';
import type { RunCache } from '../harness/evaluate.js';
import { lineDiff } from '../util/diff.js';
import { GateResult } from './result.js';

export interface SnapshotOptions {
  dir: string;
  update: boolean;
  /** With --update, delete snapshot files no item claims. Off when L0 failed (the owner may just be invalid). */
  deleteStale?: boolean;
}

function displayPath(file: string) {
  const rel = path.relative(process.cwd(), file);
  return rel.startsWith('..') ? file : rel;
}

export function snapshotPath(dir: string, owner: string) {
  return path.join(dir, `${owner}.snap`);
}

export async function renderSnapshot(owner: string, snippets: Snippet[], cache: RunCache): Promise<{ text?: string; error?: string }> {
  const parts = [`# L3 snapshot for ${owner}. Generated by \`pnpm verify --update\`. Review diffs; never hand-edit.`, ''];
  for (const s of snippets) {
    const run = await cache.run(s.code, s.cycles);
    if (!run.ok) return { error: `${s.key} does not evaluate (see L1), so it can't be snapshotted` };
    parts.push(`## ${s.key} | cycles ${s.cycles} | cps ${run.cps}`, ...run.shows, '');
  }
  return { text: parts.join('\n') };
}

export async function gateL3(content: ValidContent, snippets: Snippet[], cache: RunCache, opts: SnapshotOptions): Promise<GateResult> {
  const r = new GateResult('L3');
  const byOwner = new Map<string, Snippet[]>();
  for (const s of snippets) {
    if (!byOwner.has(s.owner)) byOwner.set(s.owner, []);
    byOwner.get(s.owner)!.push(s);
  }
  const noSnapshot = new Set(content.variants.filter((v) => !v.v.verify.snapshot).map((v) => v.v.id));
  const expected = new Set<string>();
  if (opts.update) mkdirSync(opts.dir, { recursive: true });
  for (const [owner, list] of byOwner) {
    if (noSnapshot.has(owner)) {
      r.pass(owner, 'snapshot disabled (verify.snapshot: false)');
      continue;
    }
    expected.add(owner);
    const file = snapshotPath(opts.dir, owner);
    const rel = displayPath(file);
    const { text, error } = await renderSnapshot(owner, list, cache);
    if (error) {
      r.fail(owner, error);
      continue;
    }
    const old = existsSync(file) ? readFileSync(file, 'utf8') : null;
    if (opts.update) {
      if (old !== text) writeFileSync(file, text!);
      r.pass(owner, old === null ? `snapshot written: ${rel}` : old === text ? 'snapshot unchanged' : `snapshot UPDATED: ${rel} (review the diff)`);
      continue;
    }
    if (old === null) r.fail(owner, `snapshot missing: ${rel}. Run \`pnpm verify --update\` and review the new file`);
    else if (old !== text) r.fail(owner, `haps differ from ${rel}:\n${lineDiff(old.split('\n'), text!.split('\n'))}\n  (if the change is intended, run \`pnpm verify --update\` and review)`);
    else r.pass(owner, `matches ${rel} (${list.length} snippet(s))`);
  }
  if (existsSync(opts.dir)) {
    for (const f of readdirSync(opts.dir).sort()) {
      if (!f.endsWith('.snap')) continue;
      const owner = f.slice(0, -5);
      if (expected.has(owner)) continue;
      if (opts.update && opts.deleteStale !== false) {
        unlinkSync(path.join(opts.dir, f));
        r.pass(owner, `stale snapshot ${f} deleted`);
      } else r.fail(owner, `stale snapshot ${f}: no snapshotted variant or lesson has this id. Run \`pnpm verify --update\` to delete it`);
    }
  }
  return r;
}
