/// <reference types="vitest/config" />
import { existsSync, realpathSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

const here = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

// Content: the verified bundle (generated by `pnpm verify`, gitignored) if present,
// otherwise the schema-conforming fixture. Unit tests always use the fixture.
const realBundle = path.join(here, 'src/content/bundle.json');
const fixtureBundle = path.join(here, 'src/content/fixture.bundle.json');
const isTest = !!process.env.VITEST;
const forceFixture = process.env.TUDEL_FIXTURE === '1';
const useFixture = isTest || forceFixture || !existsSync(realBundle);
const bundlePath = useFixture ? fixtureBundle : realBundle;

// One Strudel instance: @strudel/web ships a self-contained bundle of core + webaudio + superdough.
// @strudel/draw and @strudel/soundfonts import '@strudel/core' / '@strudel/webaudio' directly, which
// would load a *second* copy (separate soundMap, separate Pattern prototype). Alias both to the
// @strudel/web bundle, which re-exports every name they import. See docs/decisions/0102.
const strudelWeb = realpathSync(path.join(path.dirname(require.resolve('@strudel/web/package.json')), 'dist/index.mjs'));

export default defineConfig({
  base: './',
  plugins: [react()],
  define: {
    __CONTENT_IS_FIXTURE__: JSON.stringify(useFixture),
  },
  resolve: {
    alias: [
      { find: '@content-bundle', replacement: bundlePath },
      { find: /^@strudel\/(core|webaudio)$/, replacement: strudelWeb },
      { find: /^@strudel\/web$/, replacement: strudelWeb },
    ],
  },
  build: {
    target: 'es2022',
    chunkSizeWarningLimit: 2500,
  },
  preview: { port: 4173, strictPort: true },
  test: {
    environment: 'node',
    include: ['src/**/*.test.{ts,tsx}'],
    setupFiles: ['src/test-setup.ts'],
    coverage: {
      provider: 'v8',
      include: ['src/srs/**/*.ts', 'src/store/**/*.ts', 'src/session/**/*.ts'],
      exclude: ['**/*.test.ts', '**/*.d.ts'],
      reporter: ['text', 'text-summary'],
      thresholds: { lines: 90 },
    },
  },
});
