/**
 * Loads the content bundle. `@content-bundle` is a Vite alias (vite.config.ts) for
 * src/content/bundle.json when it exists (generated by `pnpm verify`), else fixture.bundle.json.
 */
import raw from '@content-bundle';
import { Bundle as BundleSchema, type Bundle } from '@tudel/content-schema';
import { indexBundle, type ContentIndex } from './indexBundle';

/** True when the app runs on the fixture bundle (shows a visible "FIXTURE CONTENT" banner). */
export const isFixtureContent: boolean = __CONTENT_IS_FIXTURE__;

function load(): Bundle {
  if (import.meta.env.DEV) {
    // Validate in dev and tests; production trusts the verifier, which validated at build time.
    const r = BundleSchema.safeParse(raw);
    if (!r.success) throw new Error(`content bundle failed schema validation: ${r.error.message}`);
    return r.data;
  }
  return raw as Bundle;
}

export const bundle: Bundle = load();
export const content: ContentIndex = indexBundle(bundle);
export type { ContentIndex };
